FROM python:3.12-slim

WORKDIR /app

# 安装依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir cryptography>=41.0.0  # To fix the connection issue in mysql
# 复制脚本
COPY ./watcher/ . 

# 创建数据目录
RUN mkdir -p /data/reports

# 暴露 Prometheus 端口
EXPOSE 8000

# 运行
CMD ["python", "-u", "main.py"]
